// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 

=  Installation

:doctype: book
:toc: left
:toclevels: 3
:toc-position: left
:toc-title: Apache Karaf
:numbered:


Apache Karaf is a lightweight container, very easy to install and administer, on both Unix and Windows platforms.

==  Requirements

Storage: ::

* 50 MB of free disk space for the Apache Karaf binary distribution.

Operating Systems: ::

* Windows: Windows 8, Windows 7, Windows 2003, Windows Vista, Windows XP SP2, Windows 2000.
* Unix: RedHat Enterprise Linux, Debian, SuSE/OpenSuSE, CentOS, Fedora, Ubuntu, MacOS, AIX, HP-UX, Solaris, any Unix platform that supports Java.

Environment: ::

* Java SE 1.7.x or greater ([http://www.oracle.com/technetwork/java/javase/]).
* The Java SE "bin" directory has to be in the `PATH` environment variable, or the `JAVA_HOME` environment variable must be set to point to the directory where the Java SE distribution is installed.

==  Using Apache Karaf binary distributions

Apache Karaf is available in two distributions, and in either a "tar.gz" or "zip" format.

The "default" distribution is a "ready to use" distribution, with everything provided in the distribution archive.

The "minimal" distribution is like many minimal distributions for other applications.
Only the core layer is provided, and most of the features and bundles are downloaded from the Internet at bootstrap.
This means that the Apache Karaf minimal distribution requires an Internet connection to fully install itself. Once the "minimal" distribution fully installs, it provides all the same features as the "default" distribution.

=== Installation on Windows platform

. From a browser, navigate to [http://karaf.apache.org/index/community/download.html].
. Download Apache Karaf binary distribution in the zip format: `apache-karaf-n.n.n.zip` (like `apache-karaf-4.0.1.zip`).
. Extract the files from the zip file into a directory of your choice (where `KARAF_HOME` points to).
Note: remember the restrictions concerning illegal characters in Java paths, e.g. \!, % etc.
. Apache Karaf is now installed.

[TIP]
====
Handy Hint::
In case you have to install Karaf into a very deep path or a path containing illegal characters for Java paths, e.g. \!, % etc., you may add a bat file to _start \-> startup_ that executes
`subst S: "C:\your very % problematic path!\KARAF"`
so your Karaf root directory is S: --- which works for sure and is short to type.
====

=== Installation on Unix platforms

. From a browser, navigate to [http://karaf.apache.org/index/community/download.html].
. Download Apache Karaf binary distribution in the tar.gz format: `apache-karaf-n.n.n.tar.gz`  (like `apache-karaf-4.0.1.tar.gz`).
. Extract the files from the tar.gz file into a directory of your choice (where `KARAF_HOME` points to). For example:
----
gunzip apache-karaf-n.n.n.tar.gz
tar xvf apache-karaf-n.n.n.tar
----

or
----
tar xvzf apache.karaf-n.n.n.tar.gz
----
Note: remember the restrictions concerning illegal characters in Java paths, e.g. \!, % etc.
. Apache Karaf is now installed.

==  Post-Installation steps

Apache Karaf uses Java, so it has to be able to find the "java" executable.  No matter what platform you're on, this is done by either putting the "bin" directory of the Java SE distribution into the `PATH` environment variable, or by setting the `JAVA_HOME` environment variable to point to the root of the Java SE distribution.

By default, all Apache Karaf files are available in one directory: the `KARAF_HOME`.

You can define your own directory layout, by using some Karaf environment variables:

* `KARAF_DATA` is the location of the data folder, where Karaf stores temporary files.
* `KARAF_ETC` is the location of the etc folder, where Karaf stores configuration files.
* `KARAF_BASE` is the Karaf base folder. By default `KARAF_BASE` is the same as `KARAF_HOME`.

==  Building from Sources

If you intend to build Apache Karaf from the sources, the requirements are a bit different:

Storage: ::

* 500 MB of free disk space for the Apache Karaf source, the Maven build outputs, and the external dependencies downloaded by Maven.

Environment: ::

* Java SE Development Kit 1.7.x or greater ([http://www.oracle.com/technetwork/java/javase/]).
* Apache Maven 3.0.3 (or newer) ([http://maven.apache.org/download.html]).

=== Building on Windows platform

. You can get the Apache Karaf sources from:
* the sources distribution `apache-karaf-n.n.n-src.zip` available at [http://karaf.apache.org/index/community/download.html]. Extract the files in the directory of your choice.
* by checkout of the git repository:
----
git clone https://git-wip-us.apache.org/repos/asf/karaf.git karaf
----
. Use Apache Maven to build Apache Karaf:
----
mvn clean install
----
Note: you can speed up the build by bypassing the unit and integration tests:
----
mvn clean install -DskipTests
----
. You can find the built binary distribution in `assemblies\apache-karaf\target\apache-karaf-n.n.n.zip`. You can install and use it as explained in the "Using Apache Karaf binary distributions" section.

=== Building on Unix platforms

. You can get the Apache Karaf sources from:
* the sources distribution `apache-karaf-n.n.n-src.tar.gz` available at [http://karaf.apache.org/index/community/download.html]. Extract the files in the directory of your choice.
* by checkout of the git repository:
----
git clone https://git-wip-us.apache.org/repos/asf/karaf.git karaf
----
. Use Apache Maven to build Apache Karaf:
----
mvn clean install
----
Note: you can speed up the build by bypassing the unit and integration tests:
----
mvn clean install -DskipTests
----
. You can find the built binary distribution in `assemblies/apache-karaf/target/apache-karaf-n.n.n.tar.gz`. You can install and use it as explained in the "Using Apache Karaf binary distributions" section.
