// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 

=  Features XML Schemas (provisioning)

Apache Karaf 3.0.0 supports different versions of the features XML schemas.

The features XML schema can be found directly in the Apache Karaf sources, in the `features/core` module:

----
features/core/src/main/resources/org/apache/karaf/features/karaf-features-1.2.0.xsd
features/core/src/main/resources/org/apache/karaf/features/karaf-features-1.1.0.xsd
features/core/src/main/resources/org/apache/karaf/features/karaf-features-1.0.0.xsd
----

These schemas are also available on the Apache Karaf website:

* [http://karaf.apache.org/xmlns/features/v1.2.0]
* [http://karaf.apache.org/xmlns/features/v1.1.0]
* [http://karaf.apache.org/xmlns/features/v1.0.0]

==  karaf-features-1.2.0.xsd

{snippet:url=../features/core/src/main/resources/org/apache/karaf/features/karaf-features-1.2.0.xsd|lang=xml|pygmentize=true}
{snippet}

==  karaf-features-1.1.0.xsd

{snippet:url=../features/core/src/main/resources/org/apache/karaf/features/karaf-features-1.1.0.xsd|lang=xml|pygmentize=true}
{snippet}

==  karaf-features-1.0.0.xsd

{snippet:url=../features/core/src/main/resources/org/apache/karaf/features/karaf-features-1.0.0.xsd|lang=xml|pygmentize=true}
{snippet}