/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_felix_examples_simple_Activator */

#ifndef _Included_org_apache_felix_examples_simple_Activator
#define _Included_org_apache_felix_examples_simple_Activator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_felix_examples_simple_Activator
 * Method:    foo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_felix_examples_simple_Activator_foo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
