// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 

== Goal _karaf:features-generate-descriptor_

Except in unusual circumstances, use the `<packaging>feature</packaging>` to run this goal.

The _karaf:features-generate-descriptor_ goal generates a features XML file based on the Maven dependencies. By default, it will follow Maven transitive dependencies, stopping when it encounters bundles already present in features that are Maven dependencies.

A record of the dependency tree search can be found in _target/history/treeListing.txt._

You can track dependency changes and warn or fail on change.

== Configuration

Specify the packaging as a top level element

----
<packaging>feature</packaging>
----

You can supply a feature descriptor to extend in src/main/feature/feature.xml.

[cols="1,1,5"]
|===
| Parameter Name | Type | Description 
| aggregateFeatures | boolean (false) | Specifies processing of feature repositories that are (transitive) Maven dependencies. If false, all features in these repositories become dependencies of the generated feature.  If true, all features in these repositories are copied into the generated feature repository. 
| startLevel | int | The start level for the bundles determined from Maven dependencies.  This can be overridden by specifying the bundle in the source feature.xml with the desired startlevel. 
| includeTransitiveDependency | boolean (true) | Whether to follow Maven transitive dependencies. 
| checkDependencyChange | boolean (false) | Whether to record dependencies in src/main/history.dependencies.xml for change tracking. 
| warnOnDependencyChange | boolean (false) | whether to fail on changed dependencies (false, default) or warn in the build output (true). 
| logDependencyChanges | boolean (false) | If true, added and removed dependencies are shown in target/history. 
| overwriteChangedDependencies 
| boolean (false) 
| If true, the src/main/history/dependencies.xml file will be overwritten if it has changed.
|===


=== Example
[source,xml]
----
<project>
...
  <packaging>feature</packaging>
  <dependencies>
    <dependency>
      <groupId>org.apache</groupId>
      <artifactId>bundle1</artifactId>
      <version>1.0</version>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.karaf.tooling</groupId>
        <artifactId>karaf-maven-plugin</artifactId>
        <version>${project.version}</version>
        <extensions>true</extensions>
          <configuration>
            <startLevel>80</startLevel>
            <aggregateFeatures>true</aggregateFeatures>
          </configuration>
        </plugin>
    </plugins>
  </build>
</project>
----
