package org.apache.karaf.main.lock;

/**
 * Allows to react on events generated by the locking framework
 */
public interface LockCallBack {
    void lockAquired();
    void lockLost();
    void waitingForLock();
}
