#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: CI

on:
  push:
    branches: [ "main", "karaf-4.4.x" ]
  pull_request:
    branches: [ "main", "karaf-4.4.x" ]

jobs:
  build:
    name: build (${{ matrix.os }})

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build
        run: mvn -U -B -e clean install -Prat -DskipTests "-Dinvoker.skip=true"
      - name: Save Maven Local Repository
        uses: actions/upload-artifact@v7
        with:
          name: maven-local-repo-${{ matrix.os }}-${{ github.run_id }}
          path: ~/.m2/repository
          retention-days: 1

  test:
    name: test (${{ matrix.os }})
    needs: build

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Restore Maven Local Repository
        uses: actions/download-artifact@v8
        with:
          name: maven-local-repo-${{ matrix.os }}-${{ github.run_id }}
          path: ~/.m2/repository
      - name: Test
        run: mvn -B -e install -Ptest
        timeout-minutes: 180
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results-${{ matrix.os }}
          path: '**/target/surefire-reports/*.xml'
      - name: Upload Event File
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: event-file-${{ matrix.os }}-${{ github.run_id }}
          path: ${{ github.event_path }}
